# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pajita' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pajita
	pod 'MBProgressHUD'
  pod 'Toast-Swift'
#  pod 'AlamofireObjectMapper', '~> 6.2'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'iOSDropDown'
  pod 'SwiftSignatureView'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
end
